### ISSUE TITLE
Property editor doesn't work in Shadow DOM

### ISSUE THREAD

**Issue by talimarcus** [PredixDev/px-demo#13]
The modal opens up, but the code editor itself isn't actually in there. Works fine in Shady DOM.

![screen shot 2017-06-15 at 5 14 50 pm](https://user-images.githubusercontent.com/9092541/27206797-934ccf22-51ee-11e7-9019-b17c322c70c6.png)

**Comment by randyaskin** [comment]
Seems to be working fine post-hybrid-upgrade. Tested in both Polymer 1 and 2 shadow dom modes.
