### ISSUE TITLE
Something weird happening with data editor

### ISSUE THREAD

**Issue by mdwragg** [PredixDev/px-demo#2]
Just seen this, px-data-table link on predix-ui.com

<img width="1200" alt="screen shot 2017-02-27 at 10 47 24 pm" src="https://cloud.githubusercontent.com/assets/3594714/23394589/e854dc94-fd3e-11e6-984c-edda0ab69c47.png">

**Comment by benoitjchevalier** [comment]
Where you in shadow dom? Looks like the "shadow dom bug" we have noticed recently with our demos. 
The ace widget doesn't work in our demos in shadow dom at the moment, so if you have at least one property using the json editor it fails.
Should work in shady dom.

**Comment by mdwragg** [comment]
Nope, was shady dom. Though interested to hear more about this bug - @PredixDev/px can somebody point me to the issue we're tracking this in please?

**Comment by benoitjchevalier** [comment]
Don't think it was tracked yet. To repro just run a new demo in shadow dom, the ace editor should display an error in the console (can't find some element with a specific class, probably searching outside of its local dom)

**Comment by randyaskin** [comment]
@davidrleonard fixed this yesterday afternoon, has to do with the iron-resize behavior.

**Comment by mdwragg** [comment]
Do we need to do anything to cascade it to all repos? Was broken last night.

**Comment by mdwragg** [comment]
Also we need to track n fix that shadow dom bug - shadow dom is coming y'all.

**Comment by randyaskin** [comment]
I've re-kicked builds of data-table, dropdown, and inbox which I think were the three that would have picked up this bug yesterday morning.

**Comment by mdwragg** [comment]
Ah, cool. Thank you! @randyaskin 💯

**Comment by randyaskin** [comment]
The builds picked up the latest (v1.1.3) of px-code-editor, I've cleared my local cache and purged CloudFlare and I'm still seeing the display issue. Professor Leonard will have to take a look at the fix he put in yesterday I think.

**Comment by davidrleonard** [comment]
I think this was fixed in 8757dc6 (v1.4.12), but I messed up and didn't push a tag with the commit. Pushed a tag for v1.4.12. I'll rebuild a few demos and make sure it fixes the issue.

**Comment by randyaskin** [comment]
Now that S3 / Travis is behaving again this morning, I re-re-re-kicked the builds - looking good now. 👍

**Comment by davidrleonard** [comment]
Quick note that px-code-editor@d2061821b7b511189601e85cbf9c461855dfd687 solves the Shadow DOM problems reported by @benoitjchevalier. Styles and beautify extensions now load in Shadow DOM and Shady DOM.
