### ISSUE TITLE
Props container looks odd on IE/FF

### ISSUE THREAD

**Issue by benoitjchevalier** [PredixDev/px-demo#6]
IE:
![screen shot 2017-03-09 at 3 30 12 pm](https://cloud.githubusercontent.com/assets/3206342/23775393/5400c548-04dd-11e7-91e3-6ae193da0ff8.png)

FF:
![screen shot 2017-03-09 at 3 30 08 pm](https://cloud.githubusercontent.com/assets/3206342/23775389/502ca1f8-04dd-11e7-8ea1-a67ffb4f6a22.png)

**Comment by randyaskin** [comment]
Fixed in v1.4.19, will get picked up in subsequent re-builds.

**Comment by benoitjchevalier** [comment]
still seeing the issue in 1.5.9
