### ISSUE TITLE
Dropdown gets hidden in certain browser height, making it unusable.

### ISSUE THREAD

**Issue by ppeyro** [PredixDev/px-demo#9]
## Expected behavior and actual behavior:

In predix-ui.com, noticed this while the browser debugger is open.  The dropdown in demo-properties container opens "up" to fit the screen size; however, it gets hidden behind its parent making the dropdown unusable.  The only way to get out of it is to resize the browser height.

## Steps to reproduce the problem:

Resize the browser height to be shorter, and open the dropdown.
See the attached screenshot.

## Environment:

px-dropdown#4.0.0-prerelease-1
Browsers: All (IE11, safari9, FF54, Chrome 57)

## Screenshot:
![drop_up_dropdown](https://cloud.githubusercontent.com/assets/10835611/25407286/a416af74-29be-11e7-8cac-5607c04ca05b.png)

## Code examples 

N/A

**Comment by randyaskin** [comment]
Fixed in v2.
